[project]
name = "psyduck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "numpy>=2.3.3",
    "scikit-learn>=1.7.2",
    "sentence-transformers>=5.1.0",
]
